# Generated by Django 3.2.8 on 2021-11-06 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип',
            },
        ),
        migrations.RenameField(
            model_name='user',
            old_name='surename',
            new_name='surname',
        ),
        migrations.RemoveField(
            model_name='event',
            name='category',
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.BooleanField(default=True),
        ),
    ]
