# Generated by Django 3.2.8 on 2021-11-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_board', '0003_auto_20211106_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registrations',
            field=models.ManyToManyField(to='activities_board.Event'),
        ),
    ]
