# Generated by Django 3.2.8 on 2021-11-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_board', '0005_alter_user_registrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registrations',
            field=models.ManyToManyField(blank=True, to='activities_board.Event'),
        ),
    ]
