# Generated by Django 3.2.8 on 2021-11-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities_board', '0006_alter_user_registrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.ManyToManyField(blank=True, to='activities_board.Category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registrations',
            field=models.ManyToManyField(blank=True, to='activities_board.Event', verbose_name='Зарегестрирован на мероприятия'),
        ),
    ]
