# Generated by Django 3.2.8 on 2021-11-24 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities_board', '0008_auto_20211124_0848'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='eventName',
        ),
    ]
