# Generated by Django 3.2.8 on 2021-11-29 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities_board', '0010_auto_20211124_1049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='registrations',
        ),
        migrations.CreateModel(
            name='Registrations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities_board.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities_board.user')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, through='activities_board.Registrations', to='activities_board.Event', verbose_name='Зарегестрирован на мероприятия'),
        ),
    ]
