# Generated by Django 3.2.8 on 2021-12-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities_board', '0013_auto_20211129_1853'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrations',
            options={'ordering': ['user']},
        ),
    ]
