# Generated by Django 3.2.8 on 2021-12-13 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities_board', '0014_alter_registrations_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registrations',
            options={},
        ),
    ]
